### ISSUE TITLE
I can't scrap Hotels.com

### ISSUE THREAD

**Issue by juseoljae** [dimitryzub/hotels-scraper-js#5]
first, I did below
  **npm i hotels-scraper-js**

then, **GetHotelsCom.js** is very simple
import { hotelsCom, saveToJSON } from "hotels-scraper-js";
hotelsCom.getHotels().then(saveToJSON);

then,
  **node GetHotelsCom.js**

it occurs error
D:\Web\hotelsScrap\hotels-scraper-js-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:258
        throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'textContent')
    at pptr://__puppeteer_evaluation_script__:7:38
    at Array.map (<anonymous>)
    at pptr://__puppeteer_evaluation_script__:2:121
    at ExecutionContext._ExecutionContext_evaluate (D:\Web\hotelsScrap\hotels-scraper-js-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:258:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\Web\hotelsScrap\hotels-scraper-js-main\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:146:16)
    at async getHotelsInfo (file:///D:/Web/hotelsScrap/hotels-scraper-js-main/node_modules/hotels-scraper-js/hotelsComParser/getHotelsComHotels.js:39:10)
    at async getHotelsComHotels (file:///D:/Web/hotelsScrap/hotels-scraper-js-main/node_modules/hotels-scraper-js/hotelsComParser/getHotelsComHotels.js:361:19)

Node.js v18.17.1

can you help me?

**Comment by QuentinSc** [comment]
The package need an update, same for airbnb :/

**Comment by Sv-Shok** [comment]
Could you tell me what exactly needs to be updated?

**Comment by dimitryzub** [comment]
Hey guys, this package is no longer being maintained.

Regarding the issue both with Hotels.com and Airbnb. Most likely it's due to CSS selector change.

In other words, CSS selector on the website doesn't match CSS selector in the parser and thus it can't get anything from the website  `Cannot read properties of null (reading 'textContent')`

For Hotels, it's here: 
- https://github.com/dimitryzub/hotels-scraper-js/blob/main/hotelsComParser/getHotelsComHotels.js

If it's the case, you need to change CSS selectors in the parser.

Or it could be something else.
